### Test index page

GET http://localhost:8080/fixtures/ed25519.pk
Range: bytes=0-100


### Test tower server
GET http://localhost:8080/Cargo.toml
Range: bytes=0-100
Accept-Encoding: gzip

### Test index page
GET http://localhost:8080/fixtures/index.html
Range: bytes=0-100
Accept-Encoding: gzip